// packages/only-react/src/MyComponent.js
import React, {Component} from 'react';
import moment from 'moment';
import _ from 'lodash';

export default class MyComponent extends Component {

  render() {
    return (
      <div>
        Hello, World! {`________${_.random(100)}_${_.uniqueId('s123_')}_${moment().add(2, 'd').toISOString()}`}
      </div>
    );
  }
}

// packages/with-stencil/src/components/my-component/my-component.tsx
import { Component, Prop, h } from '@stencil/core';
import { format } from '../../utils/utils';
import moment from 'moment';
import _ from 'lodash';

@Component({
  tag: 'my-component',
  styleUrl: 'my-component.css',
  shadow: true
})
export class MyComponent {
  /**
   * The first name
   */
  @Prop() first: string;

  /**
   * The middle name
   */
  @Prop() middle: string;

  /**
   * The last name
   */
  @Prop() last: string;

  private random() : string {
    return `________${_.random(100)}_${_.uniqueId('s123_')}_${moment().add(2, 'd').toISOString()}`
  }

  private getText(): string {
    return format(this.first, this.middle, this.last) + this.random();
  }

  render() {
    return <div>Hello, World! I'm {this.getText()}</div>;
  }
}
